### ISSUE TITLE
Count me in! 

### ISSUE THREAD

**Issue by tlycken** [fsprojects/AProjectHasNoName#5]
I saw a link here posted on Twitter, and of course I want to help!

The readme has a number of suggestions for tooling - how fixed is that list? I think it would make sense to do as much as possible in the dotnet cli realm, and not mix with eg paket. If there are no objections, I could start setting up a CI pipeline on eg Appveyor and/or Travis to get things started.

**Comment by nosami** [comment]
I think paket would be used to fetch the dependency on FSharp.Compiler.Service

**Comment by forki** [comment]
> I think it would make sense to do as much as possible in the dotnet cli realm

what do you mean exactly? paket is part of that.

But the list is not fixed at all.

**Comment by tlycken** [comment]
Maybe I'm misunderstanding (it's been a while since I used either Fake or Paket - not since .NET Core came out, and I haven't built anything relying on the compiler services, ever) but IIUC the main reason for using Fake is to orchestrate compiling, testing, versioning and packaging, and the main reason to use Paket is to be able to pin dependency versions and not have transient dependencies making you go insane. With the .NET Core SDK (regardless of targeting platform), you basically get all of that within the `dotnet` CLI. Your build script can be as simple as three or four CLI commands, and you don't need the paket or lock files at all because the project files handle that (very similarly) for you OOTB. But maybe I'm missing something important?

**Comment by forki** [comment]
Ok. I don't want to got too much into details, but dotnet cli and PackageReferences does not solve the issue at all. Especially around transitive dependecies you now have new issues (if you don't explicitly lock the versions). Much bigger than with pakages.config before.
I don't think they will arise here in this tool since the deps graph will be very small.

> three or four CLI commands

experience shows that this is just not true. All projects I know start to grow around that after the first "we don't need that" phase. Handling build and test and pack is only the small and easy part. Add documentation generation, publishing to various sources, integration testing and so on. You will end up with some kind of build / deploy script. And very very soon.

**Comment by tlycken** [comment]
My recent OSS experiences differ from that, but maybe that's just because those projects were small enough with few enough contributors to not reach the pain threshold. Point taken, and my PR for a build system will include Fake and Paket :)

**Comment by forki** [comment]
Don't get me wrong I don't want to put that as something we have to do. It's more that there are still good reasons to do so, but we can start small and add that later. It's not important at all.
The important part is to have reliable local builds and CI on linux and windows. And good tests.

**Comment by markpattison** [comment]
I have been playing with using FAKE and Paket with the dotnet cli, so I'm happy to help with that.

**Comment by tlycken** [comment]
@markpattison nice! I just pushed #7, where I've outlined a stumble stone I fell on just now; I can push the non-working code there as well if you want to take a look.

**Comment by tforkmann** [comment]
I would like to contribute as well. I could help with testing it later on. If you want...

**Comment by forki** [comment]
welcome aboard!

2018-01-03 9:04 GMT+01:00 Tim Forkmann <notifications@github.com>:
